name: Update Proxy Configs
on:
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch:
permissions:
  contents: write
jobs:
  update-configs:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout current repository
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Checkout Free-Server repository
      uses: actions/checkout@v3
      with:
        repository: m3hdiclub/Free-Server
        token: ${{ secrets.PAT_TOKEN }}
        path: Free-Server
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Run config fetcher
      run: python src/fetch_configs.py
    
    - name: Debug Output
      run: |
        echo "Current directory contents:"
        ls -la
        echo "Checking if subscription file exists:"
        if [ -f "subscription" ]; then
          echo "subscription file found"
          cat subscription | wc -l
        else
          echo "subscription file NOT found"
        fi
    
    - name: Copy subscription file
      run: |
        if [ -f "subscription" ]; then
          cp subscription Free-Server/
          echo "File copied successfully"
        else
          echo "subscription file not found"
          exit 1
        fi
    
    - name: Commit and push to Free-Server repo
      run: |
        cd Free-Server
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add subscription
        git commit -m "Update subscription" || echo "No changes to commit"
        git push
