name: Update Proxy Configs
on:
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch:
permissions:
  contents: write
jobs:
  update-configs:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout current repository
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        path: current-repo
    
    - name: Checkout Free-Server repository
      uses: actions/checkout@v3
      with:
        repository: m3hdiclub/Free-Server
        token: ${{ secrets.PAT_TOKEN }}
        path: Free-Server
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
    
    - name: Install dependencies
      run: |
        cd current-repo
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Run config fetcher
      run: |
        cd current-repo
        python src/fetch_configs.py
    
    - name: Generate performance chart
      run: |
        cd current-repo
        python src/generate_charts.py
    
    - name: Update README with latest stats
      run: |
        cd current-repo
        sed -i "s|channel-stats-chart.svg?v=.*|channel-stats-chart.svg?v=$(date +%s)|" README.md
    
    - name: Commit and push current repository changes
      run: |
        cd current-repo
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add configs/channel_stats.json assets/channel_stats_chart.svg README.md
        git diff --quiet && git diff --staged --quiet || (git commit -m "Update stats and charts" && git push)
    
    - name: Commit and push Free-Server changes
      run: |
        cd Free-Server
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add subscription
        git diff --quiet && git diff --staged --quiet || (git commit -m "Update subscription file" && git push)
